language: cpp
dist: bionic

before_install:
  - sudo apt-get install -y ninja-build
  - sudo apt-get install -y curl libpng-dev libjpeg-dev zlib1g-dev libxml2-dev sqlite3 
  - sudo apt-get install -y libsdl1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl-net1.2-dev
  - sudo apt-get install -y libgl1-mesa-dev
  
script:
  - mkdir build && cd $_
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
  - ninja
  - ninja xmoto_pack
  - ninja install
 
addons:
apt:
  update: true
  packages:
  - cmake
