language: cpp
dist: bionic

before_install:
  - sudo apt-get install -y ninja-build
  - sudo apt-get install -y curl
  - sudo apt-get install -y libsqlite3-dev libjpeg62-dev libbz2-dev liblua5.1-0-dev zlib1g-dev libpng12-dev libglu1-mesa-dev libcurl3-openssl-dev libxdg-basedir-dev libxml2-dev
  - sudo apt-get install -y libgl1-mesa-dev
  
script:
  - mkdir build && cd $_
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
  - ninja
  - ninja xmoto_pack
  - ninja install
 
addons:
apt:
  update: true
  packages:
  - cmake
